version: "3.7"

services:
  # Jupyter Notebook
  notebook:
    build: ./notebook-image
    #depends_on:
    #  - jena
    ports:
      - "8889:8889"
    env_file:
      - ./docker-data/config.env
    volumes:
      - ./notebooks:/home/jovyan/

  # We want this docker container to run an RStudio instance
  rstudio: 
      # What to build
      build: .
      # Environmental File for passwords etc.
      env_file:
          - ./secret.env
    
      # Tag the built Dockerfile this name
      image: akemberling/oisst_mainstays
      
      # Ports, not entirely sure what this does?
      ports: 
          - "8787:8787"
      
      # Mapping the connections between things on our local system to the docker container
      #volumes:
      #    - ~/Documents/Repositories/oisst_mainstays : /Home/rstudio/oisst_mainstays/data
