---
format: 
  html:
    page-layout: full
    self-contained: true
    css:
      - https://cdn.knightlab.com/libs/juxtapose/latest/css/juxtapose.css
execute: 
  echo: false
  warning: false
  message: false
  comment: ""
  fig.align: center
---

```{r}
#| label: packages
#| include: false
#| echo: false
#| warning: false

####  Packages  ####
library(lubridate)
library(here)
library(scales)
library(gmRi)
library(heatwaveR)
library(tidyverse)

conflicted::conflict_prefer("select", "dplyr")
conflicted::conflict_prefer("filter", "dplyr")
conflicted::conflict_prefer("lag", "dplyr")

# Support Functions
source(here("R/oisst_support_funs.R"), verbose = FALSE)
source(here("R/temp_report_support.R"), verbose = FALSE)

# Box paths
oisst_path <- cs_path("res", "OISST/oisst_mainstays")

# File paths for various extents based on "apershing_gulf_of_maine"
region_paths <- get_timeseries_paths(region_group = "gmri_sst_focal_areas", 
                                     box_location = "cloudstorage")

```



```{ojs}
//| output: false
require("https://cdn.jsdelivr.net/npm/juxtaposejs@1.1.6/build/js/juxtapose.min.js")
  .catch(() => null)
```


```{r}
#| label: regional-sst-setup

# Timeseries Path +
timeseries_path <- region_paths[["apershing_gulf_of_maine"]][["timeseries_path"]]


# Load timeseries of SST for Region
region_timeseries <- read_csv(timeseries_path, 
                              col_types = cols(), 
                              guess_max = 1e5) 


# Format timeseries for group estimates
region_timeseries <- region_timeseries %>% 
  mutate(
    time = as.Date(time),
    area_wtd_f = as_fahrenheit(area_wtd_sst),
    anom_f     = as_fahrenheit(area_wtd_anom, "anomalies")) %>% 
  distinct(time, .keep_all = T) %>% 
  supplement_season_info() 


# Run climatology for old reference period
sst_old <- pull_heatwave_events(
  temperature_timeseries = region_timeseries,
  threshold = 90, 
  clim_ref_period = c("1982-01-01", "2011-12-31")) %>% 
  supplement_hw_data() %>% 
  filter(doy != 366)

# Run climatology for new reference period
sst_new <- pull_heatwave_events(
  temperature_timeseries = region_timeseries,
  threshold = 90, 
  clim_ref_period = c("1982-01-01", "2022-12-31"), detrend = T) %>% 
  supplement_hw_data() %>% 
  filter(doy != 366)


```




::: {.juxtapose data-startingposition="65%" style="margin-bottom:2em; width = 70%; height =70%"}

```{r}
#| fig.height: 8
#| label: fig-heatmap-comparison-old

base_date <- as.Date("2000-01-01")
grid_old <- sst_old %>% 
  mutate(year = year(time),
         yday = yday(time),
         flat_date = as.Date(yday-1, origin = base_date),
         yr_rev = factor(year),
         yr_rev = fct_rev(yr_rev),
         clim_ref = "Climatological Reference Period: 1982-2011") 


# All years:
grid_old %>% 
  heatwave_heatmap_plot(temp_units = "F", start_yr = 1981, end_yr = 2022) +
  labs(y = "Year",
       x = "Month",
       title = NULL,
       caption = "") +
  theme(legend.position = "bottom",
        legend.title = element_text(angle = 0),
        plot.margin = margin(b = 0, t = 20)) +
  facet_wrap(~clim_ref) + 
  guides(fill = guide_colorbar(
    title = "Sea Surface Temperature Anomaly",
    title.position = "top", 
    title.hjust = 0.5, barwidth = unit(3.5, "in"), 
    barheight = unit(0.5, "cm"), 
    frame.colour = "black", 
    ticks.colour = "black"))
```



```{r}
#| fig.height: 8
#| label: fig-heatmap-comparison-new

base_date <- as.Date("2000-01-01")
grid_new <- sst_new %>% 
  mutate(year = year(time),
         yday = yday(time),
         flat_date = as.Date(yday-1, origin = base_date),
         yr_rev = factor(year),
         yr_rev = fct_rev(yr_rev),
         clim_ref = "Climatological Reference Period: 1982-2022 De-Trended") 


# All years:
grid_new %>% 
  heatwave_heatmap_plot(temp_units = "F", start_yr = 1981, end_yr = 2022) +
  labs(y = "Year",
       x = "Month",
       title = NULL,
       caption = "") +
  theme(legend.position = "bottom",
        legend.title = element_text(angle = 0),
        plot.margin = margin(b = 0, t = 20)) +
  facet_wrap(~clim_ref) + 
  guides(fill = guide_colorbar(
    title = "Sea Surface Temperature Anomaly",
    title.position = "top", 
    title.hjust = 0.5, barwidth = unit(3.5, "in"), 
    barheight = unit(0.5, "cm"), 
    frame.colour = "black", 
    ticks.colour = "black"))
```
:::
